---
title: "r_DataExp"
output: html_document
date: "2023-08-28"
---

```{r}
library(tidyverse)
library(sf)
library(terra)
library(ncdf4)
```

```{r}
mask = rast("prepared/Mask/Mask.tif")

int_month = 5
```

```{r}
tick <- st_read('prepared/Tick_Reports/tick_reports_training.gpkg')
plot(st_geometry(tick))

```

```{r}
tick$month=format(tick$datetime,'%m')

tick_may = tick[tick$month == str_pad(int_month, 2, pad = "0"),]
n_obs = nrow(tick_may)

tick_may_tr = vect(tick_may)

tick_raster = rasterize(tick_may_tr, mask, fun = 'sum') 

tick_raster = subst(tick_raster, NA, 0)

```

## Covariates

```{r}
resample_proj = function(rast_1, method = 'average'){
  x = project(rast_1, crs(mask))
  resample(x, mask, method = 'average')
}
```

### Elevation

```{r}
# Import elevation raster
elev = rast('prepared/DHM/DHM25.tif')

# Assign correct CRS
crs(elev) = "EPSG:21781"

# Join the elevation data
elev_res2mask = resample_proj(elev)

stack = c(tick_raster, elev_res2mask)

plot(stack)
```

### Weather

```{r}
# Function to calculate the aggregated monthly data of weather variables for May
may_avg = function(dir_name, na_val = 0){

  files = list.files(dir_name, pattern="*.nc$")
  
  files = files[1:6] # Hard code 
  
  k = 1
  
  for (i in files) {
    
    ras = rast(paste0(dir_name,i))
          
    crs(ras) = 'EPSG: 2056'

    ras = subst(ras, NA, na_val)
    
    # Get May data
    may = ras[[int_month]]
    
    if (nlyr(ras) == 12){
      if (k == 1){
        may_stack = may
      } else {
        may_stack = c(may_stack, may)
    }
    }
    
    k = k + 1
    
  }
  
  mean_may = app(may_stack, mean)
  crs(mean_may) = crs(ras)
  
  
  mean_may
}
```

#### Precipitation

```{r}
P_may = may_avg('prepared/Weather/RhiresM/')

stack = c(stack, resample_proj(P_may))
```

#### Relative Humidity

```{r}
RH_may = may_avg('prepared/Weather/SrelM/', NA)

stack = c(stack, resample_proj(RH_may))
```

#### Temperature

```{r}
T_may = may_avg('prepared/Weather/TabsM/', NA)

stack = c(stack, resample_proj(T_may))
```

### Covariate visualization

```{r}

names(stack) = c("Tick_oc", "elev", 'precipitation', 'rel_hum', 'temperature')

# writeRaster(stack,"test.tif", overwrite = T)

plot(stack)

```

### Additional covariates (Soil)

```{r}
if (!('Predictors' %in% list.files('prepared'))){
  options(timeout=600)
  download.file('https://www.envidat.ch/dataset/4ab13d14-6f96-41fd-96b0-b3ea45278b3d/resource/e0faab13-0d1b-492a-8539-5370d48b9e35/download/predictors.zip', 'prepared/predictors.zip')
  unzip('prepared/predictors.zip', exdir = 'prepared')
  unlink('prepared/predictors.zip', recursive = T)
}
```

```{r}

for (i in list.files('prepared/Predictors')){
  
  soil = rast(paste0('prepared/Predictors/',i)) #CRS 3395

  crs(soil) = "EPSG:3395"
  
  stack = c(stack, resample_proj(soil))
  
}


plot(stack) #Water bodies should be cropped out
```

```{r}
writeRaster(stack, 'most_covs.tif', overwrite = T)
```

### OSM data

#### Hiking trails

```{r}
hik = svc('HikingPaths_Switzerland.geojson')
hik = project(hik[[2]], 'EPSG:2056')

hik$presence = 1

n = rasterize(hik, mask, field = 'presence')

distance_hiking_trails = distance(n)

num_hik = focal(n, 5, fun = 'sum')

writeRaster(distance_hiking_trails, 'dist_hike.tif', overwrite = T)
writeRaster(num_hik,'num_hik.tif', overwrite = T)
```

### All paths

```{r}
all = svc('paths.geojson')
all = project(all[[2]], 'EPSG:2056')

all$presence = 1

n = rasterize(all, mask, field = 'presence')

distance_path = distance(n)

num_path = focal(n, 5, fun = 'sum')

writeRaster(distance_path, 'dist_path.tif', overwrite = T)
writeRaster(num_path,'num_path.tif', overwrite = T)
```
